### ISSUE TITLE
Workload distribution - PS1

### ISSUE THREAD

**Issue by juliansibaja84** [karolaya/PDI#2]
### Andrés Simancas Mateus
Punto 6, 4
### Julián Sibaja García
Punto 5, 7
### Karolay Ardila Salazar
Punto 1, 2, 3, 8

**Comment by asmateus** [comment]
Already done 4, 5 and 6. I needed to do the fifth item as a prerequisite of the sixth.

**Comment by juliansibaja84** [comment]
8 Done
